"""empty message

Revision ID: 39d2ff01913
Revises: 41ef3d6a5be
Create Date: 2015-05-06 10:20:56.998382

"""

# revision identifiers, used by Alembic.
revision = '39d2ff01913'
down_revision = '41ef3d6a5be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artisttags', ['artist_id', 'tag_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artisttags', type_='unique')
    ### end Alembic commands ###
