"""empty message

Revision ID: 41ef3d6a5be
Revises: 4ccfc6da46e
Create Date: 2015-05-06 10:05:27.070590

"""

# revision identifiers, used by Alembic.
revision = '41ef3d6a5be'
down_revision = '4ccfc6da46e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('name', sa.Unicode(length=128), nullable=True))
    op.drop_column('tracklists', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracklists', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('album', 'name')
    ### end Alembic commands ###
