"""empty message

Revision ID: 4ccfc6da46e
Revises: 337aac9737d
Create Date: 2015-05-06 10:02:26.674067

"""

# revision identifiers, used by Alembic.
revision = '4ccfc6da46e'
down_revision = '337aac9737d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['id'], ['tracklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=128), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tracklists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('tracklists', sa.Column('type', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracklists', 'type')
    op.drop_table('playlist')
    op.drop_table('album')
    ### end Alembic commands ###
